openedx/credentials-themes

edx_credentials_themes/static/mitpe/css/mitpe.certificate.style-ltr.css
edx_credentials_themes/static/mitpe/css/mitpe.certificate.style-rtl.css
edx_credentials_themes/static/mitpe/sass/_layouts-rendering.scss
edx_credentials_themes/static/mitpe/sass/_print-rendering.scss
edx_credentials_themes/templates/mitpe/credentials/programs/base.html

MIT requested some changes regarding design of their cert. This changes the org logo size, the seal size, and breaks the signatory title onto two lines.
[WL-1164]

Update MIT cert styling

---

edx_credentials_themes/static/mitpe/css/mitpe.certificate.style-ltr.css
edx_credentials_themes/static/mitpe/css/mitpe.certificate.style-rtl.css
edx_credentials_themes/templates/mitpe/credentials/programs/base.html
edx_credentials_themes/templates/mitpe/credentials/programs/c8f689f4-8418-41bd-a73b-64c1459c1bb2/certificate.html
edx_credentials_themes/templates/mitpe/credentials/programs/d670134d-3155-4b8a-b058-4618bb2b3e2c/certificate.html

Titles longer than 42 chars are split into title and subtitle for
formatting purposes. Currently subtitle is not passed into the template
content, so for the time being program titles must be overriden in
order for the certificate to display the correct title.
This will be fixed once WL-1120 is complete and subtitle can be added
to the context.

Allow override of program title.

---

edx_credentials_themes/templates/mitpe/credentials/programs/d5b225db-1597-4677-b202-31ba5a18613e/certificate.html
edx_credentials_themes/templates/mitpe/credentials/programs/f4cb742d-93fd-4463-8b30-d730c0b1eec3/certificate.html

Because we're still doing this stupid thing where every time a
program is ran we create a new program and the dates aren't dynamically
overwritten in the template.

Adds certs for new SysEng programs

---

README.rst

This wiki explains how to test local changes in credentials-themes and is good to have referenced directly in the READMe for people to find easily.

Update READMe to reference wiki

---

.travis.yml

Fixing warnings from travis config (ex. https://travis-ci.com/github/edx/credentials-themes/jobs/429157893/config)
Values taken from credentials: https://github.com/edx/credentials/blob/master/.travis.yml

MICROBA-646 Fix travis config warnings

---

.github/CODEOWNERS

Add codeowners file to help with PR notifications.
Reference: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
MICROBA-977

build: Add codeowners file to help with PR notifications

---

.github/workflows/patch_version_on_requirements_update.yml

Copied from another workflow that had `__version__` between double quotes.

Update version bump workflow for single quote

---

README.rst

Use public doc page since @iloveagent57 kindly moved the content

docs: Use public doc page

---

.github/workflows/create_tag_on_merge_to_master.yml

[MICROBA-1673]
When the `credentials-themes` repo transitioned to the `openedx` GitHub org this automation broke as the `openedx` org doesn't have access to the `EDX_DEPLOYMENT_GH_TOKEN` secret. This change attempts to fix the automation by using another token/user that we believe has the correct permissions.
We _can't_ use the automatically generated `GITHUB_TOKEN` as this would prevent further downstream automation from running after the version is successfully tagged. See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret.

fix: update token used in our merge-to-master tagging github action

---

.github/workflows/create_credentials_requirements_pr.yml

[MICROBA-1673]
Update another one of our GitHub actions to use the `REQUIREMENTS_BOT_GITHUB_TOKEN` over `EDX_DEPLOYMENT_GH_TOKEN` (which we no longer have access to). See also: https://github.com/openedx/credentials-themes/pull/401

fix: Update token used in a few more GitHub actions scripts

---

requirements/pip_tools.txt

Manually update the `pip-tools.txt` generated file to fix an issue with
`pip` and `pip-tools`. `pip 22.x` and `pip-tools <6.5` are not compatible with
each other. Normally, we shouldn't modify a generated file but we are
stuck without doing it this time.

fix: manually update pip-tools to unbreak workflow

---

.tx/config

The credentials-theme Transifex project has moved to a new organization.
This updates the configuration to point to the new repository.

fix: Use new Transifex project.

---

.github/workflows/upgrade-python-requirements.yml

* Adjusts the cron schedule of the `upgrade-python-requirements` job to run on Tuesday.

chore: adjust `upgrade requirements` job to run on Tuesday

---

.github/workflows/upgrade-python-requirements.yml

The `edx-aperture` team doesn't seem to exist anymore. I believe it may have been renamed to `2U-aperture` which would explain the reason the automation can't add the correct reviewers.

fix: fix team tagging issue causing the Python upgrade automation to throw an error

---

.github/workflows/add-to-project.yml
catalog-info.yaml

This PR adds the catalog-info.yaml, which records the ownership of this repo. Its use is described in [OEP-55](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html)
* The OSPR bot will now add pull requests to projects if directed to by catalog-info.yaml.

chore: add catalog-info yaml and automation that adds new PRs to repo

---

package.json
webpack.config.js

I was looking at a renovate PR that is trying to update `glob` from v8 --> v9. After taking another look, I realized that we aren't even using `glob` anymore. We removed its use in 2019. This PR removes `glob` from our `package.json` and removes the only use of the package in this repo.
Removed here: https://github.com/openedx/credentials-themes/commit/fbd835d3b32d084489848d5dc809253a5ce69fd5

chore: remove glob dependency

---

.github/workflows/create_credentials_requirements_pr.yml

This will fix an issue with the PRs opened automatically in Credentials (after a `credentials-themes` update) failing the "Lint commit message" check in CI.

build: update commit message used in workflow to be compliant with conventional commits

---

.github/workflows/create_credentials_requirements_pr.yml

This reverts commit 4b68a1a77e9dfb25fc0b0dac095ae7b793b18b37, which looks to have caused issues with our CI.

revert: revert "chore(deps): update actions/github-script action to v7 (#735)"

---

.github/workflows/create_credentials_requirements_pr.yml

This reverts commit 1e5cc82db526eca104062315c3270f3ac3b03e67 as it causes a workflow between credentials-themes and credentials to fail.

revert: update actions/github-script action to v7 (#745)

---

.github/workflows/upgrade-python-requirements.yml
.gitignore

* on github, the group has a lowercase `u`.
* adding vscode to gitignore
FIXES: APER-3306

feat:  changing the case of the group to notify

---

.github/workflows/create_credentials_requirements_pr.yml

[APER-3679]
Upgrades the version of Python used by the `create_credentials_requirements_pr` workflow to 3.11.
This ensures that the requirements generated for Credentials will be using the same version of Python currently configured for Credentials.

chore: upgrade version of Python used in workflow

---

.github/workflows/create_credentials_requirements_pr.yml

This fix is based on a recommendation from a GH issue in the `github-script` repository: https://github.com/actions/github-script/issues/448#issuecomment-1966857829

fix: github-script v7 regression

---

.github/workflows/create_credentials_requirements_pr.yml

Renovate is being overly helpful again and upgraded the version of Python used in the `create_credentials_requirements_pr` workflow to 3.13. This is causing issues with the Credentials IDA, as this workflow is responsible for updating all of the Credentials IDA's requirements files.

chore: downgrade Python version used in automation to 3.12

---

requirements/constraints.txt

this constraint is for a package we no longer install, and was only necessary for Python versions we no longer install.
FIXES: APER-3294

chore: removing unnecessary constraint
